apiVersion: v1
kind: Service
metadata:
  name: rest
  namespace: lab7
spec:
  selector:
    app: rest
  type: ClusterIP
  ports:
    - name: http
      port: 8080        # external service port
      targetPort: 5000  # MUST MATCH the app.run port
